miniproject/common/urls.py
from django.urls import path, include
from . import views
#from .views import MyLoginView

app_name = 'common'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('mypage/',views.mypage, name='mypage'),
    path('orderhistory/<int:user_id>/',views.orderhistory, name='orderhistory'),
    path('createhistory/<int:user_id>/',views.createhistory, name='createhistory'),
    path('signup/success', views.signup_success, name='signup_success'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),

]

miniproject/miniproject/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talent.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

miniproject/talent/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'talent'

urlpatterns =[
    path('', views.index, name='index'),
    path('productcreate/', views.product_create, name='ProductCreate'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/payment/<int:product_id>/',views.payment, name="payment"),
    path('cart/delete/<int:product_id>/', views.delete, name='delete'),
    path('cart/delete_all/', views.delete_all, name='delete_all'),
    path('cart/payment_all/', views.payment_all, name='payment_all'),
    path('reviewcreate/', views.review_create, name='ReviewCreate'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miniproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.min.js"></script>
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
	<style>
		.carousel-image {
		  width: 100%; /* 원하는 가로 크기로 설정 */
		  height: 400px; /* 원하는 세로 크기로 설정 */
		  background-position: center;
		  background-repeat: no-repeat;
		  background-size: cover;
		}
	</style>
</head>
<body>
	{% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:index' %}";
        </script>
    {% endif %}
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div id="banner-carousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators">
		<li data-target="#banner-carousel" data-slide-to="0" class="active"></li>
		<li data-target="#banner-carousel" data-slide-to="1"></li>
		<li data-target="#banner-carousel" data-slide-to="2"></li>
		<li data-target="#banner-carousel" data-slide-to="3"></li>
		<!-- 추가적인 인디케이터가 있으면 여기에 추가 -->
		</ol>
	
		<!-- Slides -->
		<div class="carousel-inner">
		<div class="carousel-item active">
			<div class="carousel-image" style="background-image: url({% static '배너1.jpeg' %});"></div>
		</div>
		<div class="carousel-item">
			<div class="carousel-image" style="background-image: url({% static '배너2.jpeg' %});"></div>
		</div>
		<div class="carousel-item">
			<div class="carousel-image" style="background-image: url({% static '배너3.jpeg' %});"></div>
		</div>
		<div class="carousel-item">
			<div class="carousel-image" style="background-image: url({% static '배너4.jpeg' %});"></div>
		</div>
		<!-- 추가적인 슬라이드가 있으면 여기에 추가 -->
		</div>
	
		<!-- Controls -->
		<a class="carousel-control-prev" href="#banner-carousel" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#banner-carousel" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
		</a>
	</div>
	<!-- Navbar2 -->
  {% include "navbar2.html" %}
  <!-- 메인 리스트 -->
	{% block content %}
	{% endblock %}
  {% block script %}
   {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/navbar1.html
	{% load static %}
	<head>
		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
		<!-- Customer 스타일 추가 -->
		<link rel="stylesheet" href="{% static 'nav.css'%}">
		<link rel="stylesheet" href="{% static '/fonts/font.css'%}">
	</head>	
	<!-- Navbar -->
	<nav class="navbar navbar-expand-lg">
		<a class="navbar-brand" style="font-size: 35px;"href="{% url 'talent:index' %}">찬 웅 이 네  ☺︎  강 의 사 이 트</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link1" href="{% url 'common:mypage' %}">{{ user.username }} 님 환영합니다.</a>
					</li>	
					<li>
						<a class="nav-link1" href="{% url 'account_logout' %}">로그아웃</a>
					</li>
					<li class="nav-item">
						<a class="nav-link1" href="{% url 'talent:ProductCreate' %}">강의 등록</a>
					</li>
					<li class="nav-item">
						<a class="nav-link1" href="{% url 'talent:cart' %}">장바구니</a>
					</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link1" href="{% url 'common:login' %}">로그인</a>
				</li>
				<li class="nav-item">
					<a class="nav-link1" href="{% url 'common:signup' %}">회원가입</a>
				</li>
				{% endif %}
				<!-- 추가적인 네비게이션 메뉴 항목들을 이곳에 추가할 수 있습니다 -->
			</ul>
		</div>
	</nav>
	

miniproject/templates/navbar2.html
{% load static %}
<link rel="stylesheet" href="{% static 'nav.css'%}">
	<!-- Navbar -->
	<style>
		.navbar2{
			background: linear-gradient(to right, #DC143C, #87c);
		}
		.nav-link2{
			color: white !important;
			font-family:'Shinb7';
			font-size: 30px;
		}
	</style>
	<nav class="navbar2 navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav2" aria-controls="navbarNav2" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav2">
			<ul class="navbar-nav mx-auto">
                <li class="nav-item">
					<a class="nav-link2" href="{% url 'talent:index' %}">전체</a>
				</li>
				{% for categorys_obj in categorys %}
				<li class="nav-item">
					<a class="nav-link2" href="{% url 'talent:category' category_id=categorys_obj.id %}">{{categorys_obj.category}}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
	</nav>

miniproject/templates/navbar3.html
{% load static %}
<link rel="stylesheet" href="{% static 'nav.css'%}">
	<!-- Navbar -->
	<style>
		.navbar3{
			background: linear-gradient(to right, #DC143C, #87c);
		}
		.nav-link3{
			color: white !important;
			font-family:'Shinb7';
			font-size: 30px;
		}
	</style>
	<nav class="navbar3 navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav2" aria-controls="navbarNav2" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav2">
			<ul class="navbar-nav mx-auto">
                <li class="nav-item">
					<a class="nav-link3" href="{% url 'common:mypage' %}">마이페이지</a>
				</li>
				<li class="nav-item">
					<a class="nav-link3" href="{% url 'common:createhistory' user_id=request.user.id %}">강의 내역</a>
				</li>
				<li class="nav-item">
					<a class="nav-link3" href="{% url 'common:orderhistory' user_id=request.user.id %}">주문 내역</a>
				</li>
			</ul>
		</div>
	</nav>

miniproject/templates/navbar4.html
{% load static %}

	<!-- Navbar -->
	<style>
		.navbar4{
			background: linear-gradient(to right, #DC143C, #87c);
		}
		.nav-link4{
			color: transparent !important;
			font-family:'Shinb7';
			font-size: 30px;
		}
	</style>

	<nav class="navbar4 navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav2">
			<ul class="navbar-nav mx-auto">
				<li class="nav-item">
					<a class="nav-link4"> .</a>
				</li>
			</ul>
		</div>
	</nav>

miniproject/templates/navbar5.html
{% load static %}

	<!-- Navbar -->
	<style>
		.navbar4{
			background: linear-gradient(to right, #DC143C, #87c);
		}
		.nav-link4{
			color: white !important;
			font-family:'Shinb7';
			font-size: 30px;
		}
	</style>

	<nav class="navbar4 navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav2">
			<ul class="navbar-nav mx-auto">
				<li class="nav-item">
					<a class="nav-link4"> 로그인 </a>
				</li>
			</ul>
		</div>
	</nav>

miniproject/templates/navbar6.html
{% load static %}

	<!-- Navbar -->
	<style>
		.navbar4{
			background: linear-gradient(to right, #DC143C, #87c);
		}
		.nav-link4{
			color: white !important;
			font-family:'Shinb7';
			font-size: 30px;
		}
	</style>

	<nav class="navbar4 navbar-expand-lg navbar-light bg-light">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav4" aria-controls="navbarNav4" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNav2">
			<ul class="navbar-nav mx-auto">
				<li class="nav-item">
					<a class="nav-link4"> 회원가입 </a>
				</li>
			</ul>
		</div>
	</nav>