miniproject/common/urls.py
from django.urls import path, include
from . import views
#from .views import MyLoginView

app_name = 'common'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('mypage/',views.mypage, name='mypage'),
    path('orderhistory/<int:user_id>/',views.orderhistory, name='orderhistory'),
    path('createhistory/<int:user_id>/',views.createhistory, name='createhistory'),
    path('signup/success', views.signup_success, name='signup_success'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),

]

miniproject/miniproject/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talent.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

miniproject/talent/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'talent'

urlpatterns =[
    path('', views.index, name='index'),
    path('productcreate/', views.product_create, name='ProductCreate'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/payment/<int:product_id>/',views.payment, name="payment"),
    path('cart/delete/<int:product_id>/', views.delete, name='delete'),
    path('cart/delete_all/', views.delete_all, name='delete_all'),
    path('cart/payment_all/', views.payment_all, name='payment_all'),
    path('reviewcreate/', views.review_create, name='ReviewCreate'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miniproject/talent/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    # use column
    email = models.EmailField(max_length=50, unique=True)
    password = models.CharField(max_length=1000)
    username = models.CharField(max_length=20, unique=True)
    birth = models.DateField(null=True)
    gender = models.CharField(max_length=15)
    phone_number = models.CharField(max_length=30)
    profile_image = models.ImageField(upload_to='profiles/', null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    # delete colume
    first_name = None
    last_name = None
    last_login = None
    date_joined = None
    
    def __str__(self):
        return self.email
    
class Category(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class Product(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=200)
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=4000)
    thumbnail_image = models.ImageField(upload_to='images/', null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class Review(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default="기본 제목")
    content = models.CharField(max_length=1000)
    like_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

class Cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class Ordered(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    price = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

miniproject/talent/forms.py
from django import forms
from .models import User, Product, Review

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = ['user_id']

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ('user_id', 'product')
        fields = ('user_id', 'product', 'title', 'content')

class ProfileImageForm(forms.Form):
    profile_image = forms.ImageField()

miniproject/talent/views.py
from django.shortcuts import render, redirect
from .forms import ProductForm, ReviewForm
from .models import Product, Cart, User, Category, Ordered, Review
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q


# Create your views here.

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    selected_value = request.GET.get('box')
    # 선택한 값에 따라 데이터를 정렬하는 로직을 구현
    if selected_value == '-created_at':
        data = Product.objects.all().order_by('-created_at')
    elif selected_value == 'created_at':
        data = Product.objects.all().order_by('created_at')
    elif selected_value == '-price':
        data = Product.objects.all().order_by('-price')
    elif selected_value == 'price':
        data = Product.objects.all().order_by('price')
    else:
        data = Product.objects.all().order_by('-created_at')  # 디폴트값으로 '-created_at'을 사용

    if kw:
        data = data.filter(
            Q(product_name__icontains=kw) |  # 제목 검색
            Q(description__icontains=kw) |  # 세부 내용 검색
            Q(user_id__username__icontains=kw)   # 판매자 이름 검색
        ).distinct()
    seller_ids = data.values_list('user_id', flat=True)
    sellers = User.objects.filter(id__in=seller_ids)
    categorys= Category.objects.all()
    user_name = request.user.username
    paginator = Paginator(data, 12)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'data':data,
               'sellers':sellers,
               'categorys':categorys,
               'user_name':user_name,
               'data':page_obj,
               'page': page, 
               'kw': kw}
    return render(request, 'talent/products_list.html',context)


@login_required
def product_create(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user_id = request.user
            product.save()
            return redirect('talent:index')  # 등록 후 상품 목록 페이지로 이동
    else:
        form = ProductForm()
    return render(request, 'talent/product_create.html', {'form': form})




def detail(request, product_id):
    data = Review.objects.filter(product_id=product_id).order_by('-created_at')
    product = Product.objects.get(id=product_id)
    seller = product.user_id
    categorys= Category.objects.all()
    form = ReviewForm()
    context = {
        'product' : product,
        'seller' : seller,
        'categorys' : categorys,
        'form' : form,
        'data' : data,
    }
    return render(request, 'talent/products_detail.html', context)

def cart(request) :
    # 사용자가 로그인한 경우에만 장바구니를 보여줌
    if request.user.is_authenticated:
        user_id = request.user.id

        # 장바구니에 있는 상품 목록을 가져옵니다.
        cart_items = Cart.objects.filter(user_id=user_id)
        products = []

        for cart_item in cart_items:
            product = cart_item.product
            products.append(product)

        context = {
            'cart_items' : cart_items,
            'user_id' : user_id,
            'products' : products,
        }
        return render(request, 'talent/cart.html', context)
    else:
        return redirect('common:login')  # 로그인 페이지로 리다이렉트

def category(request, category_id):
     data = Product.objects.filter(category_id=category_id).order_by('-created_at')
     seller_ids = data.values_list('user_id', flat=True)
     sellers = User.objects.filter(id__in=seller_ids)
     categorys= Category.objects.all()
     user_name = request.user.username

     context = {'data':data,
                'sellers':sellers,
                'categorys':categorys,
                'user_name':user_name}
     return render(request, 'talent/products_list.html',context)


def add_to_cart(request, product_id):
    # 로그인한 사용자인지 확인
    if request.user.is_authenticated:
        user_id = request.user.id
        cart_item_exists = Cart.objects.filter(product=product_id, user_id=user_id).exists()
        if cart_item_exists:
            # 이미 해당 상품이 장바구니에 있는 경우 처리 로직 작성
            # 예: 수량 증가 등
            error_message = "장바구니에 상품이 이미 추가되어 있습니다."

        else:
            # 해당 상품이 장바구니에 없는 경우 새로운 장바구니 아이템 생성
            product = Product.objects.get(id=product_id)
            cart_item = Cart.objects.create(product=product, user_id=request.user)
            cart_item.save()
            error_message = "장바구니에 상품이 추가되었습니다."
        # 장바구니 페이지로 리디렉션 또는 원하는 경로로 설정하세요.
        return render(request, 'talent/products_list.html', {'error_message':error_message})

    # 상품을 장바구니에 추가하는 로직 작성
    # 장바구니에 이미 해당 상품이 있는지 확인
    else:
         # 로그인되지 않은 경우 로그인 페이지로 이동하거나 원하는 경로로 설정하세요.
        return redirect('account:login')



def payment(request, product_id):
    Ordered.objects.create(user_id=request.user, product_id=product_id, price=Product.objects.get(id=product_id).price)
    Cart.objects.get(product_id=product_id, user_id=request.user).delete()
    error_message = "해당 상품을 구매하였습니다."
    user_id = request.user.id

    # 장바구니에 있는 상품 목록을 가져옵니다.
    cart_items = Cart.objects.filter(user_id=user_id)
    products = []

    for cart_item in cart_items:
        product = cart_item.product
        products.append(product)

    context = {
        'cart_items' : cart_items,
        'user_id' : user_id,
        'products' : products,
        'error_message':error_message,
    }
    return render(request, 'talent/cart.html', context)

def delete(request,product_id):

    cart_item = Cart.objects.get(product_id=product_id, user_id=request.user)
    cart_item.delete()
    error_message = "해당 상품이 삭제되었습니다."
    user_id = request.user.id

    # 장바구니에 있는 상품 목록을 가져옵니다.
    cart_items = Cart.objects.filter(user_id=user_id)
    products = []

    for cart_item in cart_items:
        product = cart_item.product
        products.append(product)

    context = {
        'cart_items' : cart_items,
        'user_id' : user_id,
        'products' : products,
        'error_message':error_message,
    }
    return render(request, 'talent/cart.html', context)

    
def delete_all(request):
    cart_items = Cart.objects.filter(user_id=request.user)

    for item in cart_items:
        item.delete()
    error_message = "장바구니의 모든 상품이 삭제되었습니다."
    context = {
        'error_message':error_message,
    }
    return render(request, 'talent/cart.html', context)



def payment_all(request):
    cart_items = Cart.objects.filter(user_id=request.user)

    for item in cart_items:
        Ordered.objects.create(user_id=request.user, product_id=item.product_id, price=Product.objects.get(id=item.product_id).price)
        Cart.objects.get(product_id=item.product_id, user_id=request.user).delete()
    error_message = "장바구니의 모든 상품을 구매하였습니다."
    context = {
        'error_message':error_message,
    }
    return render(request, 'talent/cart.html', context)
        

def review_create(request):
    id = request.POST.get('product_id')
    if request.method == "POST" :
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user_id = request.user
            review.product_id = id
            review.save()
            url = f'/product/{id}/'
            return redirect(url) # 등록 후 상품 상세 페이지로 이동

    else :
        pass

miniproject/templates/talent/cart.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	{% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:index' %}";
        </script>
    {% endif %}
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
{% include "navbar3.html" %}

{% block content %}
<!doctype html>
<html lang="ko">
<head>
    <!-- 필수 메타 태그 -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    <title>장바구니</title>
</head>
<body>
    {% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:cart' %}";
        </script>
    {% endif %}
    <div class="container my-3">
        <table class="table">
            <thead>
                <tr class="text-center thead-dark">
                    <th style="width:10%; font-size: 30px;">번호</th>
                    <th style="width:30%; font-size: 30px;">상품이미지</th>
                    <th style="width:25%; font-size: 30px;">상품명</th>
                    <th style="width:20%; font-size: 30px;">상품가격</th>
                    <th style="width:15%; font-size: 30px;">삭제/구매</th>
                </tr>
            </thead>
            <tbody>
            {% if cart_items %}
            {% for product in products %}
            <tr class="text-center">
                <td>
                    <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                    <h4>{{ forloop.counter }}</h4>
                </td>
                <td class="text-center">
                    <img src="{{ product.thumbnail_image.url }}" alt="..." width="300" height="170" />
                </td>
                <td class="text-center">
                    <h4>{{ product.product_name }}</h4>
                </td>
                <td class="text-center">
                    <h4>{{ product.price|intcomma }}</h4>
                </td>
                <td class="text-center">
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent d-flex justify-content-between">
                        <div><a href="{% url 'talent:delete' product_id=product.id %}" " class="btn btn-outline-dark mt-auto">삭제</a></div>
                        <div><a href="{% url 'talent:payment' product_id=product.id %}" class="btn btn-outline-dark mt-auto">구매</a></div>
                    </div>
                </td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">장바구니에 담긴 상품이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <td class="text-center">
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent d-flex justify-content-between">
                <div><a href="{% url 'talent:delete_all' %}" " class="btn btn-outline-dark mt-auto">전체 삭제</a></div>
                <div><a href="{% url 'talent:payment_all' %}" class="btn btn-outline-dark mt-auto">전체 구매</a></div>
            </div>
        </td>
    </div>
</body>
</html>
{% endblock %}

miniproject/templates/talent/product_create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	{% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:index' %}";
        </script>
    {% endif %}
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
    {% include "navbar4.html" %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'productcreate.css'%}">
    <link rel="stylesheet" href="{% static 'fonts/font.css'%}">
</head>
<!-- <form class="proc_F" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="proc_B" type="submit">Upload</button>
</form> -->


<form class="proc_F" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-field">
        <label for="{{ form.product_name.id_for_label }}">Product Name:</label>
        {{ form.product_name }}
    </div>
    <div class="form-field">
        <label for="{{ form.price.id_for_label }}">Price:</label>
        {{ form.price }}
    </div>
    <div class="form-field">
        <label for="{{ form.category.id_for_label }}">Category:</label>
        {{ form.category }}
    </div>
    <div class="form-field">
        <label for="{{ form.description.id_for_label }}">Description:</label>
        {{ form.description }}
    </div>
    <div class="form-field">
        <label for="{{ form.thumbnail_image.id_for_label }}">Thumbnail Image:</label>
        {{ form.thumbnail_image }}
    </div>
    <button class="proc_B" type="submit">Upload</button>
</form>
{% endblock %}
  {% block script %}
   {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/talent/products_detail.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
{% load static %}
<style>
  .card-img-top {
    object-fit: contain;
    object-position: center center;
    background-color: transparent;
    height: 650px;
    margin-bottom: 50px;
    border: 1px solid #f1f1f1; /* 테두리 스타일과 색상 설정 */
  }
</style>

<section class="product-detail">
  <div class="container" style="margin-bottom:200px;">
    <div class="row">
      <div class="col-md-12">
        <h2 style="text-align: center; margin: 30px 0 70px 0; font-size: 70px; font-family: 'Shinb7';">{{ product.product_name }}</h2>
      </div>
      
      <div class="col-md-12">
        <div class="row" style="height: 500px;">
            <div class="col-md-6 text-left" style="margin:auto; ">
              <img class="card-img-top" src="{{product.thumbnail_image.url}}" alt="...">
            </div>
            <div class="col-md-6 text-left" style="margin-bottom: 50px;">
		    <p class="user-info"><span class="bold-text">판매자:</span><br> {{ seller.username }}</p>
		    <p class="user-info"><span class="bold-text">연락처:</span><br> {{ seller.phone_number }}</p>

		    <p class="product-info1"><span class="bold-text">가격:</span> <span class="money">{{ product.price|intcomma }}</span></p>
              <p class="product-info"><span class="bold-text1">세부 내용</span></p>
              <p class="description" style="width: 800px; height: 300px; overflow: auto;"><span class="bold-text">:   </span>{{ product.description }}</p>              <div class="actions" style="position: relative;">
                <a href="{% url 'talent:add_to_cart' product_id=product.id %}"class="btn-cart" style="margin-top: 100px;">🛒 Add to Cart</a>
              </div>
          </div>
          
        </div>
    </div>    
  </div>
</section>




<br><br><br><br><br><br>
<section class="reviews">
  <div class="row">
  <div class="container">
    <hr>
    <h3 style="text-align: center; margin: 30px 0 70px 0; font-size: 70px; font-family: 'Shinb7';">Reviews</h3>
    <div class="actions" style="width: fit-content; margin-left: 1200px; margin-top: -90px;">
    </div>
    <br><br>
    {% if user.is_authenticated %}
      <div style="text-align: center;">
      <button class="btn btn-outline-dark mt-auto" id="open-review-modal">리뷰 작성하기</button>
    </div>
    <br><br>
    {% endif %}
  <div class="container" style="margin-bottom: 100px;">
    <div class="row">
      {% for review in data %}
      <div class="col-md-6">
        <p><strong style="font-size: 30px;">{{ review.title }}</strong></p>
        <p style="font-size: 20px;">{{ review.content }}</p>
        <p>작성자: {{ review.user_id.username }}</p>
        <p>{{ review.created_at }}</p>
        {% if request.user == review.user_id %}
        <div class="border-top-0 bg-transparent pt-0 justify-content-between" style="text-align: right;">
          <div style="display: inline-block; margin-right: 10px">
            <a href="#" class="btn btn-outline-dark mt-auto">Edit</a>
          </div>
          <div style="display: inline-block; margin-right: 50px">
            <a href="#" class="btn btn-outline-dark mt-auto">Delete</a>
          </div>
        </div>
        {% endif %}
        <hr>
      </div>
      {% empty %}
      <p style="text-align: center; font-size: 25px; margin-bottom: 100px;">작성된 리뷰가 없습니다.</p>
      {% endfor %}
    </div>
  </div>
  </div>
</div>
<!-- 모달 창 -->
<div id="review-modal" class="modal">
  <div class="modal-content">
    <button class="close" style="text-align: right";>&times;</button>
    <h3 style="text-align: center;">리뷰 작성</h3>
    <form class="review_content" method="post" action="{% url 'talent:ReviewCreate' %}" enctype="multipart/form-data">
      <input type="hidden" name="product_id" value="{{ product.id }}">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="proc_B" type="submit">등록</button>
    </form>
  
    <!-- 리뷰 작성 폼 등을 포함한 내용 -->
    <!-- ... -->
  </div>
</div>

<script>
  // 모달 창 열기
  var openModalBtn = document.getElementById("open-review-modal");
  var reviewModal = document.getElementById("review-modal");

  openModalBtn.addEventListener("click", function() {
    reviewModal.style.display = "block";
  });

  // 모달 창 닫기
  var closeModalBtn = document.getElementsByClassName("close")[0];

  closeModalBtn.addEventListener("click", function() {
    reviewModal.style.display = "none";
  });

  // 모달 창 외부 클릭 시 닫기
  // window.addEventListener("click", function(event) {
  //   if (event.target == reviewModal) {
  //     reviewModal.style.display = "none";
  //   }
  // });
</script>
</section>
{% endblock %}

miniproject/templates/talent/products_list.html
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<!-- 상품 이미지가 작으면 뒤에 배경색을 주고 가운데 정렬하게하는 style코드 -->
<style>
    .card-img-top {
      object-fit: contain;
      object-position: center;
      background-color: #f5f5f5; /* 배경화면 색상 */
      height: 220px; /* 이미지 높이를 원하는 크기로 설정 */
    }
</style>
<!-- Section-->
<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5 al">
    <div class="col-6 offset-3">
        <form id="searchForm" method="get" action="{% url 'talent:index' %}">
          <select class="form-control_select" style="margin-top: -5rem; margin-bottom: 1rem; height: 35px;" id="box" name="box" onchange="handleSortChange()">
            <label for="box">필터</label>
            <option value="" disabled selected>- 선택 -</option>
            <option value="-created_at">최신순</option>
            <option value="created_at">오래된 순</option>
            <option value="-price">높은 가격순</option>
            <option value="price">낮은 가격순</option>
          </select>
          <div class="input-group" style="margin-bottom: 3rem; height: 35px;">
            <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
          </div>
          <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
          <input type="hidden" id="page" name="page" value="{{ page }}">
          <input type="hidden" id="sort" name="sort" value="">
        </form>
    </div>
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4">
      {% for product in data %}
      <div class="col mb-5">
          <div class="card h-100">
              <img class="card-img-top" src="{{ product.thumbnail_image.url }}"alt="...">
              <div class="card-body p-4">
                  <div class="text-center">
                      <h5 class="fw-bolder" >{{ product.product_name }}
                        {% if product.review_set.count > 0 %}
                        <span class="text-danger small ml-2">({{ product.review_set.count }})</span>
                        {% endif %}
                      </h5>
                      {% for seller in sellers %}
                          {% if seller == product.user_id %}
                              <a class="fw-bolder">{{ seller.username }}</a>
                          {% endif %}
                      {% endfor %}                       
                      <p>{{ product.price| intcomma }} 원</p>
                  </div>
              </div>
              <div class="card-footer p-4 pt-0 border-top-0 bg-transparent d-flex justify-content-between">
                  <div><a href="{% url 'talent:detail' product_id=product.id %}" class="btn btn-outline-dark mt-auto">상세보기</a></div>
                  <div><a href="{% url 'talent:add_to_cart' product_id=product.id %}" class="btn btn-outline-dark mt-auto">장바구니 담기</a></div>
              </div>
          </div>
      </div>
      {% endfor %}
    </div>
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if data.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ data.previous_page_number }}"
            href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in data.paginator.page_range %}
        {% if page_number >= data.number|add:-5 and page_number <= data.number|add:5 %}
            {% if page_number == data_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if data.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ data.next_page_number }}"
                href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
  </div>
  <form id="searchForm" method="get" action="{% url 'talent:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
</section>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
const boxElement = document.getElementById("box");
    boxElement.addEventListener("change", function() {
        document.getElementById("searchForm").submit();
    });
function handleSortChange() {
    var selectedOption = document.getElementById("box").value;
    document.getElementById("sort").value = selectedOption;
    document.getElementById("searchForm").submit();
}
</script>
{% endblock %}