miniproject/common/urls.py
from django.urls import path, include
from . import views
#from .views import MyLoginView

app_name = 'common'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('signup/', views.signup, name = 'signup'),
    path('mypage/',views.mypage, name='mypage'),
    path('orderhistory/<int:user_id>/',views.orderhistory, name='orderhistory'),
    path('createhistory/<int:user_id>/',views.createhistory, name='createhistory'),
    path('signup/success', views.signup_success, name='signup_success'),
    path('activate/<str:uidb64>/<str:token>/', views.activate, name="activate"),

]

miniproject/miniproject/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('talent.urls')),
    path('common/', include('common.urls')),
    path('accounts/', include('allauth.urls')),
]

miniproject/talent/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'talent'

urlpatterns =[
    path('', views.index, name='index'),
    path('productcreate/', views.product_create, name='ProductCreate'),
    path('product/<int:product_id>/', views.detail, name='detail'),
    path('cart/', views.cart, name='cart'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/payment/<int:product_id>/',views.payment, name="payment"),
    path('cart/delete/<int:product_id>/', views.delete, name='delete'),
    path('cart/delete_all/', views.delete_all, name='delete_all'),
    path('cart/payment_all/', views.payment_all, name='payment_all'),
    path('reviewcreate/', views.review_create, name='ReviewCreate'),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miniproject/common/models.py
from django.db import models

# Create your models here.

miniproject/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from talent.models import User

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=50, help_text='이메일을 입력해주세요.')
    password1 = forms.CharField(label='비밀번호', widget=forms.PasswordInput, help_text='비밀번호를 입력해주세요.')
    password2 = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput, help_text='비밀번호를 한 번 더 입력해주세요.')
    username = forms.CharField(max_length=20, help_text='닉네임을 입력해주세요.')
    birth = forms.DateField(label='생년월일', widget=forms.DateInput(attrs={'type': 'date'}), required=False)
    gender = forms.ChoiceField(label='성별', choices=(('male', '남성'), ('female', '여성')), required=False)
    phone_number1 = forms.CharField(max_length=3, label='전화번호', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '010'}))
    phone_number2 = forms.CharField(max_length=4, label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '1234'}))
    phone_number3 = forms.CharField(max_length=4, label='', widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '5678'}))


    def clean_phone_number1(self):
        phone_number1 = self.cleaned_data['phone_number1']
        if not phone_number1.isdigit():
            raise ValidationError('숫자만 입력해주세요.')
        return phone_number1

    def clean_phone_number2(self):
        phone_number2 = self.cleaned_data['phone_number2']
        if not phone_number2.isdigit():
            raise ValidationError('숫자만 입력해주세요.')
        return phone_number2

    def clean_phone_number3(self):
        phone_number3 = self.cleaned_data['phone_number3']
        if not phone_number3.isdigit():
            raise ValidationError('숫자만 입력해주세요.')
        return phone_number3

    def clean_phone_number(self):
        phone_number1 = self.cleaned_data['phone_number1']
        phone_number2 = self.cleaned_data['phone_number2']
        phone_number3 = self.cleaned_data['phone_number3']
        phone_number = f'{phone_number1}-{phone_number2}-{phone_number3}'
        return phone_number

    def save(self, commit=True):
        user = super().save(commit=False)
        user.phone_number = self.clean_phone_number()
        if commit:
            user.is_active=False
            user.save()
        return user

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('이미 사용 중인 이메일입니다.')
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number1', 'phone_number2', 'phone_number3', 'password1', 'password2', 'birth', 'gender']

miniproject/common/views.py
from talent.models import User, Ordered, Product
from django.shortcuts import render, redirect, get_object_or_404
from talent.forms import ProfileImageForm
from .forms import SignupForm
from django.contrib.auth import login as login2,authenticate
# SMTP 관련 인증
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_str
from .tokens import account_activation_token
from django.contrib import auth


def index(request):
    return render(request, 'talent/products_list.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=True)
            current_site = get_current_site(request) 
            message = render_to_string('common/activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            mail_title = "계정 활성화 확인 이메일"
            mail_to = request.POST["email"]
            email = EmailMessage(mail_title, message, to=[mail_to])
            email.send()
            # # 사용자 인증
            # authenticated_user = authenticate(request, username=user.username, password=form.cleaned_data['password1'])
            # if authenticated_user is not None:
            #     # 인증된 사용자 로그인
            #     login2(request, authenticated_user)
            return redirect('talent:index')
        else:
            render(request, 'common/signup.html', {'form': form})
    else:
        form = SignupForm()

    return render(request, 'common/signup.html', {'form': form})

# 계정 활성화 함수(토큰을 통해 인증)
def activate(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExsit):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login2(request, user)
        return redirect("talent:index")
    else:
        return render(request, 'talent/products_list.html', {'error' : '계정 활성화 오류'})
    return 


def login(request):
    return render(request, 'common/login.html')


def mypage(request):
    user_id=request.user.id
    user = get_object_or_404(User, id=user_id)

    if request.method == 'POST':
        form = ProfileImageForm(request.POST, request.FILES)
        if form.is_valid():
            user.profile_image = form.cleaned_data['profile_image']
            user.save()
            return redirect('common:mypage', user_id=user_id)
    else:
        form = ProfileImageForm()
    
    context = {
        'user': user,
        'form': form
    }
    return render(request, 'common/mypage.html', context)

def orderhistory(request, user_id):
    # 사용자가 로그인한 경우에만 장바구니를 보여줍니다.
    if request.user.is_authenticated:
        user_id = request.user.id
        # 장바구니에 있는 상품 목록을 가져옵니다.
        orders_ = Ordered.objects.filter(user_id=user_id)
        products = []
        for order_ in orders_:
            product = order_.product
            products.append(product)
        context = {
            'orders_': orders_,
            'user_id': user_id,
            'products': products,
        }
        return render(request, 'common/orderhistory.html', context)
    else:
        return redirect('common:login')  # 로그인 페이지로 리다이렉트

def createhistory(request, user_id):
     # 사용자가 로그인한 경우에만 장바구니를 보여줍니다.
    if request.user.is_authenticated:
        user_id = request.user.id
        # 장바구니에 있는 상품 목록을 가져옵니다.
        creates_ = Product.objects.filter(user_id=user_id)
        
        products=[]
        for create_ in creates_:
            products.append(create_)
        context = {
            'creates_': creates_,
            'user_id': user_id,
            'products': products,
        }
        return render(request, 'common/createhistory.html', context)
    else:
        return redirect('common:login')  # 로그인 페이지로 리다이렉트

def signup_success(request):
    return render(request, 'common/signup_success.html')

miniproject/templates/common/activation_email.html
{{user.username}}님, 아래 링크를 클릭하여 계정을 활성화하세요:
http://127.0.0.1:8000/{% url 'common:activate' uid token %}

miniproject/templates/common/createhistory.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>찬웅이네 강의사이트</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'productdetail.css' %}">
    <link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
	<!-- Navbar2 -->
  {% include "navbar3.html" %}
  <!-- 메인 리스트 -->
	{% block content %}
  {% load humanize %}

  <section class="user-detail">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2  style="margin-top: 20px;">{{ user.username }}님의 작성 내역</h2>
        </div>
            <div class="col-md-12">
              <h3 style="margin-top: 20px;">올린 제품 목록</h3>
              <ul>
                {% if creates_ %}
                {% for product in products %}
                  <li>
                    <a href="{% url 'talent:detail' product_id=product.id %}" class="btn">{{ product.product_name }}</a>
                  </li> 
                {% endfor %}
                {% endif %}
              </ul>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
  {% block script %}
  {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	<!-- Navbar1 -->
{% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
{% include "navbar5.html" %}

{% load i18n %}
{% load account socialaccount %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Customer 스타일 추가 -->
    <link rel="stylesheet" href="{% static 'login.css'%}">
    <link rel="stylesheet" href="{% static '/fonts/font.css'%}">
  </head>
  <body class="">
    {% include "socialaccount/snippets/login_extra.html" %}
    <div id="container">
      <!-- login Box -->
      <form class = "login" method = "POST" action="{% url 'account_login' %}">
        {% csrf_token %}
        <div class="login-box">
        <div id="loginBoxTitle" style="text-align: center; font-family: 'Shinb7'; padding:5px"><a href = "{% url 'talent:index' %}">☻ 찬웅이네 ☺︎</a></div>
        <hr>
        <div class="form-group">
            <label>이메일</label>
            <input type="email" name="login" placeholder = "이메일 주소" class="form-control" value="" required id="email"  style="ime-mode:disabled; height:3rem;">
        </div>
        <div class="form-group">
            <label>비밀번호</label>
            <input type="password" name="password" class="form-control" value="" required id="id_password" autocomplete="off" style="height:3rem">
        </div>
        <div style="font-size: 1.5rem; margin-bottom: 20px;">
          <span> 아이디 저장</span> 
          <input type="checkbox" id="workSite" name="worksite" style="margin: 0px 0px 0px 10px; -webkit-transform: scale(2);">
        </div>
        <div id="login-btn-box">
          <div style="width: 100%; margin-bottom: 10px;">
            <button type="submit" id="btnLogin" class="btn btn-login-color" style="font-size: 1.5rem;">로그인</button>
          </div>
          
        <a href = "{% url 'common:signup' %}">
          <div style="width:100%;"><input type="button" id="btnSignup" value="회원가입" class="btn btn-signup-color btn-signup-font" style="font-size: 1.5rem;"></div>
          </a>
        </hr>
      </form>
        </div>
        
        

        
      </div><!-- login Box //-->
    </div>

</html>
{% endblock %}

miniproject/templates/common/mypage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	{% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:index' %}";
        </script>
    {% endif %}
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
  	<!-- Navbar3 -->
    {% include "navbar3.html" %}

{% block content %}
  {% load humanize %}
  <style>
    .profile-image-container {
      width: 400px; /* 원하는 가로 크기 */
      height: 400px; /* 원하는 세로 크기 */
      background-color: transparent; /* 원하는 배경색 */
      
      display: flex;
      justify-content: center;
      align-items: center;
    }
  
    .profile-image-container img {
      max-width: 100%;
      max-height: 100%;
    }
  </style>
  
  <section class="user-detail">
    <div class="container">
      <div class="row">
        <div class="col-md-12" style="text-align: center; margin: 50px 0 30px 0;">
          <h2 style="font-size: 50px;">{{ user.username }}</h2>
        </div>
 
      <div class="col-md-12">        
        <div class="col-md-6" style="margin:auto;"">
          {% if user.profile_image %}
          <div class="profile-image-container" style="margin:auto; text-align: center;">
            <img src="{{ user.profile_image.url }}" alt="Profile Image">
          </div>
          {% else %}
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                <label for="profile-image">Profile Image</label>
                <input type="file" class="form-control-file" id="profile-image" name="profile_image">
              </div>
              <button type="submit" class="btn btn-primary">Upload Profile Image</button>
            </form>
          {% endif %}
        </div>
      </div>

        <div class="col-md-6 text-left" style="margin:auto; ">
          <h3>Email</h3>
          <p>: {{ user.email }}</p>
          <h3>Nick Name</h3>
          <p>: {{ user.username }}</p>
          <h3>Gender</h3>
          <p>: {{ user.gender }}</p>
          <h3>Date of Birth</h3>
          <p>: {{ user.birth }}</p>
          <h3>Phone</h3>
          <p>: {{ user.phone_number }}</p>
          <!-- 추가 정보 -->
          <form>
            <p style="margin-top: 80px;">Has Joined Since: {{ user.created_at }}</p>
          </form>
        </div>
      </div>
    </div>
  </section>
	{% endblock %}
  {% block script %}
   {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/common/orderhistory.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>찬웅이네 강의사이트</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'productdetail.css' %}">
    <link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
	<!-- Navbar2 -->
  {% include "navbar3.html" %}
  <!-- 메인 리스트 -->
	{% block content %}
  {% load humanize %}

  <section class="user-detail">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h2 style="margin-top: 20px;">{{ user.username }}님의 구매 내역</h2>
        </div>
            <div class="col-md-12">
              <h3 style="margin-top: 20px;">구매한 제품 목록</h3>
              <ul>
                {% if orders_ %}
                {% for product in products %}
                  <li>
                    <a href="{% url 'talent:detail' product_id=product.id %}" class="btn">{{ product.product_name }}</a>
                  </li> 
                {% endfor %}
                {% endif %}
              </ul>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  {% endblock %}
  {% block script %}
  {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	<!-- Navbar1 -->
{% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
{% include "navbar6.html" %}
{% block content %}
<!DOCTYPE html>
<html>
    <head>
        <!-- jQuery library (served from Google) -->
        <script src="/static/jquery.min.js"></script>
        <!-- Inputmask library -->
        <script src="/static/jquery.inputmask.bundle.js"></script>
        <!-- <script src="/static/scripts.js"></script> -->
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>SIGNUP</title>
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'signup.css'%}">
        <link rel="stylesheet" href="{% static '/fonts/font.css'%}">
    </head>
    <body>
        <div class="container">
                <form class="signup-box" method="POST" action="{% url 'common:signup' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="signupBoxTitle" style="text-align: center; font-family: 'Shinb7';"><a href = "{% url 'talent:index' %}">☻ 찬웅이네 ☺︎</a></div>
                    <div></div>
                    <hr>
                        <!-- 사용자오류 표시 -->
                        {% if messages %}
                            <div class="alert alert-danger my-3" role="alert">
                                {% for message in messages %}
                                    <strong style="font-size: 20px;">{{ message.tags }}</strong>
                                    <ul><li>{{ message.message }}</li></ul>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <div class="form-group">
                            <label>이메일</label>
                            <input class="form-control" type="email" name="email" placeholder="xxxxx@xxxxxx.xxxxx">
                            <div style="display: flex; align-items: center;">
                            </div>
                        </div>
                        <div class="form-group">
                            <label>비밀번호</label>
                            <input class="form-control" type="password" name="password" placeholder="비밀번호">
                        </div>
                        <div class="form-group">
                            <label>비밀번호 확인</label>
                            <input class="form-control" type="password" name="confirm_password" placeholder="비밀번호 확인">
                        </div>
                        <div class="form-group">
                            <label>닉네임</label>
                            <input class="form-control" type="text" name="username" placeholder="닉네임">
                        </div>
                        <div class="form-group" style="background-color: white;">
                            <label for="gender">성별</label>
                            <select class="form-control_select" id="gender" name="gender">
                                <option value="" disabled selected>- 선택 -</option>
                                <option value="M">남자</option>
                                <option value="F">여자</option>
                            </select>
                        </div>
                        <div class="form-group-bir">
                            <label>생년월일</label>
                            <input class="form-control" type="date" name="birth" >
                        </div>                      
                        <div class="form-group">
                            <label>전화번호</label>
                            <input class="form-control" type="text" name="phone_number" placeholder="010-1234-5678" data-inputmask="'mask': '999-9999-9999'" onblur="checkPhoneFormat(this)">
                        </div>   

                        <div class="button-group" >
                            <div><input type="submit" id="btnsignup" value="회원가입" class="btn btn-signup-color btn-signup-font" style="width: 100%; font-size: 1.5rem;"></div>
                        </div>
                        <div class="form-group" style="text-align: right; margin-top: 10px;">
                            <a href="{% url 'common:login' %}" style="font-size: 1.5rem;">로그인 화면으로 이동하시겠습니까 ? </a>
                        </div>
                    </hr>
                </form>
            </div>                      
    </body>
</html>
{% endblock %}
{% block script %}
{% endblock %}
<!-- Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ

miniproject/templates/common/signup_success.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>찬웅이네 강의사이트</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
	<!-- Custom CSS -->
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="{% static 'productdetail.css' %}">
	<link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
	{% if error_message %}
        <script>
            alert("{{ error_message }}");
            window.location.href = "{% url 'talent:index' %}";
        </script>
    {% endif %}
	<!-- Navbar1 -->
  {% include "navbar1.html" %}
	<!-- Banner -->
	<div class="banner">
		<div class="container" style="text-align: center;">
			<img src="/static/배너이미지.jpeg" alt="배너 이미지" width="1200" style="margin: auto;">
		</div>
	</div>
	<!-- Navbar2 -->
  {% include "navbar4.html" %}
  <!-- 메인 리스트 -->
	{% block content %}

<!DOCTYPE html>
    <head>
        <title>회원가입완료</title>
    </head>

    <body>
        <h1>찬웅이네 회원이 되신 걸<br>
            축하합니다.
        </h1>
        <a href = '{% url "account_login" %}'>로그인</a>
        <a href = '/'>메인 페이지</a>
    </body>
</html>
{% endblock %}
  {% block script %}
   {% endblock %}
	<!-- Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
	integrity="sha384-tB6Ya1gLuY0FLKbLk+cfRtXmU6N3X/l1EZyLpZ